In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import layers, models
from matplotlib import pyplot as plt
from IPython.display import HTML
from tensorflow.keras.preprocessing.image import ImageDataGenerator


2026-07-30 05:48:47.226540: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-30 05:48:48.284849: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-07-30 05:48:51.649104: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [2]:
BATCH_SIZE=32

In [3]:
IMAGE_SIZE=256
CHANNELS=3


train_datagen=ImageDataGenerator(
    rescale = 1./255,
    horizontal_flip=True,
    rotation_range=10
)

train_generator = train_datagen.flow_from_directory(
    'dataset/train',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse',
)


Found 1506 images belonging to 3 classes.


In [4]:
for image_batch, label_batch in train_generator:
    print(image_batch[0])
    break

[[[0.7159612  0.7088634  0.7105492 ]
  [0.7325531  0.7265127  0.7193759 ]
  [0.76470596 0.74768496 0.7444307 ]
  ...
  [0.6313726  0.60784316 0.6156863 ]
  [0.6309847  0.6074553  0.61529845]
  [0.62988216 0.60635275 0.6141959 ]]

 [[0.71430737 0.7066582  0.7099979 ]
  [0.72704023 0.7226537  0.7149656 ]
  [0.76470596 0.7487875  0.744982  ]
  ...
  [0.624322   0.6007926  0.6086357 ]
  [0.62337446 0.59984505 0.6076882 ]
  [0.6228232  0.59929377 0.6071369 ]]

 [[0.7155123  0.7090985  0.71230537]
  [0.7243014  0.7199835  0.7133292 ]
  [0.76035357 0.745973   0.7416162 ]
  ...
  [0.62004316 0.59651375 0.6043569 ]
  [0.619724   0.59619457 0.6040377 ]
  [0.62027526 0.59674585 0.604589  ]]

 ...

 [[0.68209827 0.6624904  0.6781767 ]
  [0.6661108  0.646503   0.66218925]
  [0.6692737  0.64966583 0.6653521 ]
  ...
  [0.5586037  0.519388   0.5233096 ]
  [0.5749268  0.5357111  0.5396327 ]
  [0.5971505  0.5579348  0.5618564 ]]

 [[0.7109743  0.69136643 0.7070527 ]
  [0.71924365 0.6996358  0.7153221 ]


In [5]:
validation_datagen=ImageDataGenerator(
    rescale = 1./255,
    horizontal_flip=True,
    rotation_range=10
)

validation_genertor = train_datagen.flow_from_directory(
    'dataset/val',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse',
)

Found 215 images belonging to 3 classes.


In [6]:
test_datagen=ImageDataGenerator(
    rescale = 1./255,
    horizontal_flip=True,
    rotation_range=10
)

test_genertor = train_datagen.flow_from_directory(
    'dataset/test',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse',
)

Found 431 images belonging to 3 classes.


In [7]:
input_shape=(IMAGE_SIZE,IMAGE_SIZE,CHANNELS)
n_classes=3
model=models.Sequential([
    layers.InputLayer(input_shape=input_shape),
    layers.Conv2D(32,(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64,activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])


    
    
model.summary()

/home/vishnu/tf220/lib/python3.12/site-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(
I0000 00:00:1785390538.804879   10381 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5560 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 254, 254, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 125, 125, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 62, 62, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 60, 60, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 28, 28, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 14, 14, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 12, 12, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 6, 6, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 4, 4, 64)       │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 2, 2, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 183,747 (717.76 KB)

 Trainable params: 183,747 (717.76 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

In [9]:
model.fit(
    train_generator,
    steps_per_epoch=47,
    batch_size=32,
    validation_data=validation_genertor,
    validation_steps=6,
    verbose=1,
    epochs=20
)

Epoch 1/20


2026-07-30 05:49:04.545505: I external/local_xla/xla/service/service.cc:163] XLA service 0x7f49c0007640 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-07-30 05:49:04.545548: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA GeForce RTX 4060 Laptop GPU, Compute Capability 8.9
2026-07-30 05:49:04.614979: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-07-30 05:49:05.264667: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 92400
2026-07-30 05:49:05.340530: I external/local_xla/xla/service/gpu/autotuning/dot_search_space.cc:208] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
2026-07-30 05:49:05.

47/47 ━━━━━━━━━━━━━━━━━━━━ 63s 934ms/step - accuracy: 0.4715 - loss: 0.9484 - val_accuracy: 0.4635 - val_loss: 0.8743
Epoch 2/20
 1/47 ━━━━━━━━━━━━━━━━━━━━ 6s 144ms/step - accuracy: 0.5625 - loss: 0.8208

/home/vishnu/tf220/lib/python3.12/site-packages/keras/src/trainers/epoch_iterator.py:116: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()


47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.5625 - loss: 0.8208 - val_accuracy: 0.4583 - val_loss: 0.8965
Epoch 3/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 45s 538ms/step - accuracy: 0.6309 - loss: 0.7925 - val_accuracy: 0.7396 - val_loss: 0.6381
Epoch 4/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.7500 - loss: 0.6281 - val_accuracy: 0.6354 - val_loss: 0.7706
Epoch 5/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 28s 588ms/step - accuracy: 0.7307 - loss: 0.6313 - val_accuracy: 0.8385 - val_loss: 0.4529
Epoch 6/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 5s 93ms/step - accuracy: 0.8750 - loss: 0.4263 - val_accuracy: 0.8021 - val_loss: 0.4777
Epoch 7/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 28s 582ms/step - accuracy: 0.8833 - loss: 0.2951 - val_accuracy: 0.9219 - val_loss: 0.2602
Epoch 8/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 6s 129ms/step - accuracy: 0.9688 - loss: 0.1491 - val_accuracy: 0.8229 - val_loss: 0.4390
Epoch 9/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 30s 632ms/step - accuracy: 0.9322 - loss: 0.1875 - val_accuracy: 0.9531 - val